version: '3.1'

services:
  dp:
    container_name: ${DP_NAME}
    image: dravenk/dp-web
    ports:
      - "${DP_PORT}:80"
    environment:
      - DP_PORT=80
    volumes:
      ## If dp project not exit, please create a project into web folder.
      ## `composer create-project drupal/recommended-project dp "^9.0" -vvv`
      - ./web/dp:/var/www/html
    networks:
      - backend

####### mariadb #######
  mariadb:
    image: mariadb
    container_name: ${MARIADB_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    volumes:
      - ${PROJECT_PATH}/${MARIADB_PATH}/data:/var/lib/mysql
    networks:
      - backend

####### adminer #######
  adminer:
    image: adminer
    container_name: ${ADMINER_NAME}
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - backend

networks:
  backend: