version: '3.1'

services:

  web:
    container_name: ${NGINX_NAME}
    image: nginx
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./web/phpapp:/var/www/phpapp
      - ./config/phpapp.conf:/etc/nginx/conf.d/site.conf
    networks:
      - backend
    depends_on:
      - php

  php:
    image: php:fpm
    container_name: ${PHP_NAME}
    volumes:
      - ./web/phpapp:/var/www/phpapp
    networks:
      - backend

####### mariadb #######
  mariadb:
    image: mariadb
    container_name: ${MARIADB_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    volumes:
      - ${PROJECT_PATH}/${MARIADB_PATH}/data:/var/lib/mysql
    networks:
      - backend
####### adminer #######
  adminer:
    image: adminer
    container_name: ${ADMINER_NAME}
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - backend

networks:
  backend: